doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        mappings:
            Categoria:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Categoria/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Categoria\Domain'
                alias: Categoria
            CategoriaObjeto:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/CategoriaObjeto/Infrastructure/Persistence/Doctrine'
                prefix: 'App\CategoriaObjeto\Domain'
                alias: CategoriaObjeto
            CategoriaIntercambio:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/CategoriaIntercambio/Infrastructure/Persistence/Doctrine'
                prefix: 'App\CategoriaIntercambio\Domain'
                alias: CategoriaIntercambio
            Chat:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Chat/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Chat\Domain'
                alias: Chat
            Contacto:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Contacto/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Contacto\Domain'
                alias: Contacto
            Direccion:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Direccion/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Direccion\Domain'
                alias: Direccion
            Favorito:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Favorito/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Favorito\Domain'
                alias: Favorito
            Imagen:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Imagen/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Imagen\Domain'
                alias: Imagen
            Mensaje:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Mensaje/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Mensaje\Domain'
                alias: Mensaje
            Intercambio:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Intercambio/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Intercambio\Domain'
                alias: Intercambio
            LogIntercambio:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/LogIntercambio/Infrastructure/Persistence/Doctrine'
                prefix: 'App\LogIntercambio\Domain'
                alias: LogIntercambio
            LogObjeto:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/LogObjeto/Infrastructure/Persistence/Doctrine'
                prefix: 'App\LogObjeto\Domain'
                alias: LogObjeto
            LogReserva:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/LogReserva/Infrastructure/Persistence/Doctrine'
                prefix: 'App\LogReserva\Domain'
                alias: LogReserva
            Objeto:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Objeto/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Objeto\Domain'
                alias: Objeto
            Preferencia:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Preferencia/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Preferencia\Domain'
                alias: Preferencia
            Reserva:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Reserva/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Reserva\Domain'
                alias: Reserva
            Usuario:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Usuario/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Usuario\Domain'
                alias: Usuario
            Valoracion:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Valoracion/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Valoracion\Domain'
                alias: Valoracion